version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: webscraper_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: webscraper_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: WebScraper
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webscraper_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
